name: Compilacao e Publicacao Angular

on:
  push:
    branches:
      - main
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setando Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Altere para a versão do Node.js que você está usando

      - name: Instalando dependências
        run: npm install

      - name: Buildando app
        run: npm run build --prod  # O Angular CLI usará as configurações do angular.json

      - name: Copiar arquivos da pasta server para docs
        run: |
          cp -r docs/server/* docs/  # Copia todos os arquivos da pasta server para docs

